name: Cypress with Allure Pipeline

on:
  push:
    branches:
      - ishan

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: List directory structure for debugging (optional)
      - name: Debug Directory Structure
        run: ls -R

      # Step 3: Install dependencies in the root directory
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Cypress tests
      - name: Run Cypress Tests
        run: npm run cypress:run

      # Step 5: Generate Allure Report
      - name: Generate Allure Report
        run: |
          npm run allure:generate
          npm run allure:open

      # Step 6: Upload Allure Report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/allure-report
